//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM_Init.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVM_Init.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Windows.Input;
        ///
        ///namespace Models
        ///{
        ///    class BaseCommand : ICommand
        ///    {
        ///        private Action&lt;object&gt; execute;
        ///        private Func&lt;object, bool&gt; canExecute;
        ///
        ///        public event EventHandler CanExecuteChanged
        ///        {
        ///            add { CommandManager.RequerySuggested += value; }
        ///            remove { CommandManager.RequerySuggested -= value; }
        ///        }
        ///
        ///        public Command(Action&lt;object&gt; execute, Func&lt;object, bool&gt; canExecute = null)
        ///        {
        ///           [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BaseCommand {
            get {
                return ResourceManager.GetString("BaseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System.ComponentModel;
        ///using System.Runtime.CompilerServices;
        ///
        ///namespace ViewModels
        ///{
        ///    public class BaseViewModel : INotifyPropertyChanged
        ///    {
        ///        public event PropertyChangedEventHandler PropertyChanged;
        ///
        ///        public void OnPropertyChanged([CallerMemberName]string prop = &quot;&quot;)
        ///        {
        ///            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string BaseViewModel {
            get {
                return ResourceManager.GetString("BaseViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ContentPage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
        ///             xmlns:d=&quot;http://xamarin.com/schemas/2014/forms/design&quot;
        ///             xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///             mc:Ignorable=&quot;d&quot;
        ///             x:Class=&quot;Views.MainPage&quot;&gt;
        ///
        ///    &lt;StackLayout&gt;
        ///        &lt;!-- Place new controls here --&gt;
        ///        &lt;Label Text=&quot;Welcome to Xamarin.Forms!&quot; 
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using ViewModels;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Xamarin.Forms;
        ///
        ///namespace Views
        ///{
        ///    // Learn more about making custom code visible in the Xamarin.Forms previewer
        ///    // by visiting https://aka.ms/xamarinforms-previewer
        ///    [DesignTimeVisible(false)]
        ///    public partial class MainPage : ContentPage
        ///    {
        ///        public MainPage()
        ///        {
        ///            InitializeComponent [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MainPage_xaml {
            get {
                return ResourceManager.GetString("MainPage_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Window x:Class=&quot;Views.MainWindow&quot;
        ///        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///        mc:Ignorable=&quot;d&quot;
        ///        Title=&quot;MainWindow&quot; 
        ///        Height=&quot;450&quot; 
        ///        Width=&quot;800&quot;&gt;
        ///    &lt;Grid&gt;
        ///        
        ///    &lt;/Grid&gt;
        ///&lt;/Window&gt;
        ///.
        /// </summary>
        internal static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using ViewModels;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace Views
        ///{
        ///    /// &lt;summary&gt;
        ///    /// MainWindow.xaml codebehind
        ///    /// &lt;/summary&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MainWindow_xaml {
            get {
                return ResourceManager.GetString("MainWindow_xaml", resourceCulture);
            }
        }
    }
}
